---
- name: Deploy normalizer
  hosts: nodes
  roles:
  - role: fluentd-normalizer
    fluentd_project: test-anton
    fluentd_name: fluentd-zmq
    configs_dir: "{{ inventory_dir }}/../zmq-configs/"
    kubeconfig: /home/centos/.kube/config
